import json
import re
import sys
from collections import Counter

MAX_ALLOWED_DUPLICATE_RATIO = 0.2


def _result(passed, issues=None):
    return {"passed": passed, "issues": issues or []}


def check_formatting(lines):
    issues = []
    for idx, line in enumerate(lines, start=1):
        if "\t" in line:
            issues.append(f"Line {idx}: tab character found.")
        if line.rstrip("\n").endswith(" "):
            issues.append(f"Line {idx}: trailing whitespace found.")
        if len(line.rstrip("\n")) > 120:
            issues.append(f"Line {idx}: exceeds 120 characters.")
    return _result(not issues, issues)


def check_grammar(lines):
    issues = []
    sentence_pattern = re.compile(r"[^.!?]+[.!?]")
    text = " ".join(line.strip() for line in lines if line.strip())
    for sentence in sentence_pattern.findall(text):
        sentence = sentence.strip()
        first_alpha = next((char for char in sentence if char.isalpha()), "")
        if first_alpha and not first_alpha.isupper():
            issues.append(f"Sentence does not start with uppercase: '{sentence[:50]}'")
    if not sentence_pattern.findall(text):
        issues.append("No complete sentences detected.")
    return _result(not issues, issues)


def check_technical_contents(text):
    required_sections = [
        "abstract",
        "introduction",
        "methodology",
        "results",
        "conclusion",
    ]
    required_chapters = [
        "chapter 1",
        "chapter 2",
        "chapter 3",
        "chapter 4",
        "chapter 5",
    ]

    lower = text.lower()
    issues = []
    for section in required_sections:
        if section not in lower:
            issues.append(f"Missing required section: {section.title()}.")
    for chapter in required_chapters:
        if chapter not in lower:
            issues.append(f"Missing required chapter marker: {chapter.title()}.")
    return _result(not issues, issues)


def check_diagrams(text):
    count = len(re.findall(r"\bdiagram\b", text, flags=re.IGNORECASE))
    issues = [] if count else ["No diagram reference found."]
    return _result(not issues, issues)


def check_figures(text):
    count = len(re.findall(r"\bfigure\s+\d+", text, flags=re.IGNORECASE))
    issues = [] if count else ["No numbered figure reference found (e.g., Figure 1)."]
    return _result(not issues, issues)


def check_tables(text):
    count = len(re.findall(r"\btable\s+\d+", text, flags=re.IGNORECASE))
    issues = [] if count else ["No numbered table reference found (e.g., Table 1)."]
    return _result(not issues, issues)


def check_references(text):
    lower = text.lower()
    issues = []
    if "references" not in lower:
        issues.append("References section not found.")
    if not re.search(r"\b(19|20)\d{2}\b", text):
        issues.append("No publication year found in references.")
    return _result(not issues, issues)


def check_similarity(lines):
    normalized = [line.strip().lower() for line in lines if line.strip()]
    if not normalized:
        return _result(False, ["Document is empty."])

    counts = Counter(normalized)
    total_duplicate_occurrences = sum(count - 1 for count in counts.values() if count > 1)
    repeated_line_ratio = total_duplicate_occurrences / len(normalized)

    if repeated_line_ratio > MAX_ALLOWED_DUPLICATE_RATIO:
        return _result(
            False,
            [f"High repeated-line similarity detected ({repeated_line_ratio:.0%})."],
        )
    return _result(True)


def check_ai_contents(text):
    ai_markers = [
        r"as an ai language model",
        r"chatgpt",
        r"generated by ai",
        r"openai",
    ]
    detected_markers = [marker for marker in ai_markers if re.search(marker, text, flags=re.IGNORECASE)]
    if detected_markers:
        return _result(False, ["Potential AI-generated content marker detected."])
    return _result(True)


def check_appendices(text):
    found = bool(re.search(r"\bappendix|appendices\b", text, flags=re.IGNORECASE))
    issues = [] if found else ["Appendix/Appendices section not found."]
    return _result(not issues, issues)


def check_document(text):
    lines = text.splitlines()
    results = {
        "formatting": check_formatting(lines),
        "grammar": check_grammar(lines),
        "technical_contents": check_technical_contents(text),
        "diagrams": check_diagrams(text),
        "figures": check_figures(text),
        "tables": check_tables(text),
        "references": check_references(text),
        "similarity": check_similarity(lines),
        "ai_contents": check_ai_contents(text),
        "appendices": check_appendices(text),
    }
    results["overall_passed"] = all(result["passed"] for result in results.values())
    return results


def main():
    if len(sys.argv) != 2:
        print("Usage: python capstone_checker.py <document.txt>", file=sys.stderr)
        return 1
    path = sys.argv[1]
    with open(path, "r", encoding="utf-8") as file:
        text = file.read()
    print(json.dumps(check_document(text), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
